# Documentation: https://help.github.com/en/github/working-with-github-pages/about-github-pages-and-jekyll
theme: jekyll-theme-slate
title: Brainite.org
description: Open Source Projects

# On custom themes, this would disable "View on Github"
github:
  is_project_page: false
